TRUNCATE TABLE public.organisations RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.fundings RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.calculations RESTART IDENTITY CASCADE;
TRUNCATE TABLE public."invoiceLines" RESTART IDENTITY CASCADE;
TRUNCATE TABLE public."paymentRequests" RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.schedules RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.settlements RESTART IDENTITY CASCADE;
