#!/usr/bin/env sh

# Clone repositories managed by this project
set -e
projectRoot=$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)

(
  cd "${projectRoot}"

  printf "\nCloning repositories\n"

  test -d ffc-pay-batch-verifier\
    && >&2 echo "The 'ffc-pay-batch-verifier' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-batch-verifier.git
  test -d ffc-pay-batch-processor\
    && >&2 echo "The 'ffc-pay-batch-processor' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-batch-processor.git
  test -d ffc-pay-enrichment\
    && >&2 echo "The 'ffc-pay-enrichment' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-enrichment.git
  test -d ffc-pay-processing\
    && >&2 echo "The 'ffc-pay-processing' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-processing.git
  test -d ffc-pay-submission\
    && >&2 echo "The 'ffc-pay-submission' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-submission.git
  test -d ffc-pay-file-publisher\
    && >&2 echo "The 'ffc-pay-file-publisher' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-file-publisher.git
  test -d ffc-pay-file-receiver\
    && >&2 echo "The 'ffc-pay-file-receiver' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-file-receiver.git
  test -d ffc-pay-responses\
    && >&2 echo "The 'ffc-pay-responses' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-responses.git
  test -d ffc-pay-tracking\
    && >&2 echo "The 'ffc-pay-tracking' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-tracking.git
  test -d ffc-pay-web\
    && >&2 echo "The 'ffc-pay-web' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-web.git
  test -d ffc-pay-request-editor\
    && >&2 echo "The 'ffc-pay-request-editor' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-request-editor.git
  test -d ffc-pay-event-hub\
    && >&2 echo "The 'ffc-pay-event-hub' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-event-hub.git
  test -d ffc-pay-data-hub\
    && >&2 echo "The 'ffc-pay-data-hub' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-data-hub.git
  test -d ffc-pay-report-generator\
    && >&2 echo "The 'ffc-pay-report-generator' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-report-generator.git
  test -d ffc-pay-alerting\
    && >&2 echo "The 'ffc-pay-alerting' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-alerting.git
  test -d ffc-pay-gateway\
    && >&2 echo "The 'ffc-pay-gateway' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-gateway.git
  test -d ffc-pay-injection\
    && >&2 echo "The 'ffc-pay-injection' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-injection.git
  test -d ffc-pay-xb\
    && >&2 echo "The 'ffc-pay-xb' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-xb.git
  test -d ffc-pay-dps\
    && >&2 echo "The 'ffc-pay-dps' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-dps.git
    test -d ffc-pay-fdmr\
    && >&2 echo "The 'ffc-pay-fdmr' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-fdmr.git
  test -d ffc-pay-demographics\
    && >&2 echo "The 'ffc-pay-demographics' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-pay-demographics.git
  test -d ffc-doc-statement-data\
    && >&2 echo "The 'ffc-doc-statement-data' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-doc-statement-data.git
  test -d ffc-doc-statement-constructor\
    && >&2 echo "The 'ffc-doc-statement-constructor' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-doc-statement-constructor.git
  test -d ffc-doc-statement-generator\
    && >&2 echo "The 'ffc-doc-statement-generator' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-doc-statement-generator.git
  test -d ffc-doc-statement-publisher\
    && >&2 echo "The 'ffc-doc-statement-publisher' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-doc-statement-publisher.git
  test -d ffc-doc-statement-receiver\
    && >&2 echo "The 'ffc-doc-statement-receiver' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/ffc-doc-statement-receiver.git
)
