#!/usr/bin/env sh

echo 'ffc-pay-batch-verifier' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-batch-verifier/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-pay-batch-processor' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-batch-processor/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-pay-enrichment' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-enrichment/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-pay-processing' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-processing/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-pay-submission' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-submission/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'


echo 'ffc-pay-file-publisher' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-file-publisher/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-pay-file-receiver' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-file-receiver/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-pay-responses' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-responses/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-pay-tracking' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-tracking/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-pay-web' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-web/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-pay-request-editor' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-request-editor/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-pay-event-hub' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-event-hub/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-pay-data-hub' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-data-hub/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-pay-report-generator' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-report-generator/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-pay-alerting' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-alerting/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-pay-statement-data' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-statement-data/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-pay-statement-constructor' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-statement-constructor/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-pay-statement-generator' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-statement-generator/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-pay-statement-publisher' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-statement-publisher/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-pay-statement-receiver' &&
  curl --silent "https://api.github.com/repos/defra/ffc-pay-statement-receiver/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
