#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

show_help() {
  echo "
    Usage: path/to/ffc-pay-core [OPTION...]
    Run git pull in payment services.

    Options:
      -h, --help       display this help text
    "
}

while :; do
  case $1 in
    -h|--help)   # Call a "show_help" function to display a synopsis, then exit.
      show_help
      exit
      ;;
    *)
      break
  esac

  shift
done

cd "${projectRoot}"
cd ./ffc-pay-batch-processor && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-enrichment && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-processing && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-submission && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-responses && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-web && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-request-editor && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-batch-validator && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-file-sender && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-file-consumer && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-event && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-event-projection && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-alerts && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-mi-reporting && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-event-signalr && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-statement-data && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-statement-constructor && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-statement-generator && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-statement-publisher && \
  git pull
