#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

show_help() {
  echo "
    Usage: path/to/ffc-pay-core [OPTION...]
    Update payment services.

    Options:
      -h, --help       display this help text
    "
}

while :; do
  case $1 in
    -h|--help)   # Call a "show_help" function to display a synopsis, then exit.
      show_help
      exit
      ;;
    *)
      break
  esac

  shift
done

cd "${projectRoot}"
cd ./ffc-pay-batch-verifier && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-batch-processor && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-enrichment && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-processing && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-submission && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-file-publisher && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-file-receiver && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-responses && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-tracking && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-web && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-request-editor && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-event-hub && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-data-hub && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-report-generator && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-alerting && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-gateway && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-injection && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-mi-reporting && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-statement-data && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-statement-constructor && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-statement-generator && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-statement-publisher && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-pay-statement-receiver && \
  git checkout main && \
  git pull
