-- Table: public.completedPaymentRequests

-- DROP TABLE IF EXISTS public."completedPaymentRequests";

CREATE TABLE IF NOT EXISTS public."completedPaymentRequests"
(
    "completedPaymentRequestId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "paymentRequestId" integer,
    "schemeId" integer,
    ledger character varying(2) COLLATE pg_catalog."default",
    "sourceSystem" character varying(50) COLLATE pg_catalog."default",
    "deliveryBody" character varying(4) COLLATE pg_catalog."default",
    "invoiceNumber" character varying(30) COLLATE pg_catalog."default",
    frn bigint,
    sbi integer,
    "agreementNumber" character varying(50) COLLATE pg_catalog."default",
    "contractNumber" character varying(50) COLLATE pg_catalog."default",
    currency character varying(3) COLLATE pg_catalog."default",
    schedule character varying(3) COLLATE pg_catalog."default",
    "dueDate" character varying(10) COLLATE pg_catalog."default",
    value integer,
    acknowledged timestamp without time zone,
    "marketingYear" integer,
    "debtType" character varying(3) COLLATE pg_catalog."default",
    "recoveryDate" character varying(10) COLLATE pg_catalog."default",
    "originalSettlementDate" character varying(10) COLLATE pg_catalog."default",
    "originalInvoiceNumber" character varying(30) COLLATE pg_catalog."default",
    "invoiceCorrectionReference" character varying(30) COLLATE pg_catalog."default",
    submitted timestamp without time zone,
    "paymentRequestNumber" integer,
    invalid boolean,
    "settledValue" integer,
    "lastSettlement" timestamp without time zone,
    "referenceId" uuid,
    "correlationId" uuid,
    batch character varying(255) COLLATE pg_catalog."default",
    "paymentType" integer,
    pillar character varying(10) COLLATE pg_catalog."default",
    "exchangeRate" character varying(10) COLLATE pg_catalog."default",
    "eventDate" character varying(10) COLLATE pg_catalog."default",
    vendor character varying(10) COLLATE pg_catalog."default",
    trader character varying(10) COLLATE pg_catalog."default",
    "claimDate" character varying(10) COLLATE pg_catalog."default",
    migrated timestamp without time zone,
    "migrationId" character varying(20) COLLATE pg_catalog."default",
    "fesCode" character varying(10) COLLATE pg_catalog."default",
    "annualValue" numeric(14,2),
    "remmittanceDescription" character varying(60) COLLATE pg_catalog."default",
    "providesAccountingValues" boolean DEFAULT false,
    CONSTRAINT "completedPaymentRequestId_pkey" PRIMARY KEY ("completedPaymentRequestId")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."completedPaymentRequests"
    OWNER to postgres;

COMMENT ON COLUMN public."completedPaymentRequests"."fesCode"
    IS 'Format to be agreed with the source system and D365. Needs the ability for the scheme to have a distinct name for each configuration in D365';

COMMENT ON COLUMN public."completedPaymentRequests"."annualValue"
    IS 'Forecast annual payment value with no currency symbol. Can be a negative value.';

COMMENT ON COLUMN public."completedPaymentRequests"."remmittanceDescription"
    IS 'Text description that is shown on the remittance. Needs to be agreed with the Future RPS Team for each scheme type.';
-- Index: agreementFrnYear_completedPaymentRequests

-- DROP INDEX IF EXISTS public."agreementFrnYear_completedPaymentRequests";

CREATE INDEX IF NOT EXISTS "agreementFrnYear_completedPaymentRequests"
    ON public."completedPaymentRequests" USING btree
    ("schemeId" ASC NULLS LAST, frn ASC NULLS LAST, "marketingYear" ASC NULLS LAST, "agreementNumber" COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100)
    TABLESPACE pg_default;
-- Index: bpsRekey_completedPaymentRequests

-- DROP INDEX IF EXISTS public."bpsRekey_completedPaymentRequests";

CREATE INDEX IF NOT EXISTS "bpsRekey_completedPaymentRequests"
    ON public."completedPaymentRequests" USING btree
    ("schemeId" ASC NULLS LAST, "marketingYear" ASC NULLS LAST, frn ASC NULLS LAST, invalid ASC NULLS LAST)
    WITH (fillfactor=100)
    TABLESPACE pg_default;
-- Index: idx_completed_payment_settlement

-- DROP INDEX IF EXISTS public.idx_completed_payment_settlement;

CREATE INDEX IF NOT EXISTS idx_completed_payment_settlement
    ON public."completedPaymentRequests" USING btree
    ("paymentRequestId" ASC NULLS LAST, "lastSettlement" ASC NULLS LAST, invalid ASC NULLS LAST)
    WITH (fillfactor=100)
    TABLESPACE pg_default;
-- Index: invoiceNumber_completedPaymentRequests

-- DROP INDEX IF EXISTS public."invoiceNumber_completedPaymentRequests";

CREATE INDEX IF NOT EXISTS "invoiceNumber_completedPaymentRequests"
    ON public."completedPaymentRequests" USING btree
    ("invoiceNumber" COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100)
    TABLESPACE pg_default;
-- Index: paymentRequestNumber_completedPaymentRequests

-- DROP INDEX IF EXISTS public."paymentRequestNumber_completedPaymentRequests";

CREATE INDEX IF NOT EXISTS "paymentRequestNumber_completedPaymentRequests"
    ON public."completedPaymentRequests" USING btree
    ("paymentRequestNumber" ASC NULLS LAST)
    WITH (fillfactor=100)
    TABLESPACE pg_default;