-- Table: public.invoiceLines

-- DROP TABLE IF EXISTS public."invoiceLines";

CREATE TABLE IF NOT EXISTS public."invoiceLines"
(
    "invoiceLineId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "paymentRequestId" integer,
    "accountCode" character varying(6) COLLATE pg_catalog."default",
    "fundCode" character varying(6) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    value integer,
    "schemeCode" character varying(10) COLLATE pg_catalog."default",
    convergence boolean DEFAULT false,
    "deliveryBody" character varying(4) COLLATE pg_catalog."default",
    "agreementNumber" character varying(255) COLLATE pg_catalog."default",
    "marketingYear" integer,
    "stateAid" boolean DEFAULT false,
    invalid boolean DEFAULT false,
    CONSTRAINT "invoiceLineId_pkey" PRIMARY KEY ("invoiceLineId")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "idx_invoiceLines_paymentRequestId"
    ON public."invoiceLines" USING btree
    ("paymentRequestId" ASC NULLS LAST)
    WITH (fillfactor=100)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."invoiceLines"
    OWNER to postgres;