-- Table: public.schedule

-- DROP TABLE IF EXISTS public.schedule;

CREATE TABLE IF NOT EXISTS public.schedule
(
    "scheduleId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "paymentRequestId" integer,
    planned timestamp without time zone,
    started timestamp without time zone,
    completed timestamp without time zone,
    CONSTRAINT "scheduleId_pkey" PRIMARY KEY ("scheduleId")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.schedule
    OWNER to postgres;
-- Index: idx_schedule_payment_completed

-- DROP INDEX IF EXISTS public.idx_schedule_payment_completed;

CREATE INDEX IF NOT EXISTS idx_schedule_payment_completed
    ON public.schedule USING btree
    ("paymentRequestId" ASC NULLS LAST, completed ASC NULLS LAST)
    WITH (fillfactor=100)
    TABLESPACE pg_default;